# Generated by Django 5.2.9 on 2025-12-07 14:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codeqa", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RagSource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("path", models.CharField(max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("total_files", models.PositiveIntegerField(default=0)),
                ("total_chunks", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["-created_at", "name"],
            },
        ),
    ]
